import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  createContext,
  PropsWithChildren,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
export type Language = "en" | "my";
const my: Record<string, string> = {
  Dashboard: "ပင်မစာမျက်နှာ",
  History: "မှတ်တမ်း",
  Categories: "အမျိုးအစားများ",
  Insights: "သုံးသပ်ချက်များ",
  Profile: "ကိုယ်ရေးအချက်အလက်",
  English: "အင်္ဂလိပ်",
  Myanmar: "မြန်မာ",
  Language: "ဘာသာစကား",
  "Sign In": "အကောင့်ဝင်ရန်",
  "Sign Up": "အကောင့်ဖွင့်ရန်",
  "Forgot password?": "စကားဝှက်မေ့နေပါသလား?",
  "Email Address": "အီးမေးလ်လိပ်စာ",
  Password: "စကားဝှက်",
  "Confirm Password": "စကားဝှက်ကို အတည်ပြုပါ",
  "Continue with Google": "Google ဖြင့် ဆက်လုပ်ရန်",
  "Create account": "အကောင့်အသစ်ဖွင့်ရန်",
  "Send reset link": "စကားဝှက်အသစ်လုပ်ရန် လင့်ခ်ပို့ပါ",
  "Back to sign in": "အကောင့်ဝင်ရန် စာမျက်နှာသို့ ပြန်သွားမည်",
  "Welcome to My Finance": "My Finance မှ ကြိုဆိုပါသည်",
  "Recover your account": "သင့်အကောင့်ကို ပြန်လည်ရယူပါ",
  "Current Balance": "လက်ရှိလက်ကျန်ငွေ",
  "This Month Income": "ယခုလ ဝင်ငွေ",
  "This Month Expense": "ယခုလ ထွက်ငွေ",
  "Budget vs Actual": "လျာထားချက်နှင့် အမှန်တကယ်",
  "Recent Transactions": "လတ်တလော ငွေစာရင်းများ",
  "No transactions yet": "ငွေစာရင်း မရှိသေးပါ",
  "Tap to edit": "ပြင်ဆင်ရန် နှိပ်ပါ",
  "Tap to view": "အသေးစိတ်ကြည့်ရန် နှိပ်ပါ",
  "Financial History": "ငွေကြေးမှတ်တမ်း",
  Monthly: "လစဉ်",
  Yearly: "နှစ်စဉ်",
  Activity: "လှုပ်ရှားမှု",
  Expenses: "ထွက်ငွေ",
  Income: "ဝင်ငွေ",
  "Add New Category": "အမျိုးအစားအသစ် ထည့်ရန်",
  "Your categories": "သင့်အမျိုးအစားများ",
  CATEGORIES: "အမျိုးအစားများ",
  "List view": "စာရင်းပုံစံ",
  "Grid view": "ကွက်ယားပုံစံ",
  Transactions: "ငွေစာရင်းများ",
  Edit: "ပြင်ဆင်ရန်",
  "Personal Information": "ကိုယ်ရေးအချက်အလက်",
  Preferences: "စိတ်ကြိုက်ရွေးချယ်မှုများ",
  "Financial Settings": "ငွေကြေးဆိုင်ရာ ဆက်တင်များ",
  Appearance: "အသွင်အပြင်",
  "Light Mode": "အလင်းမုဒ်",
  "Dark Mode": "အမှောင်မုဒ်",
  "Starting Capital": "အစပြုမတည်ငွေ",
  "Spending Cap": "အသုံးစရိတ် ကန့်သတ်ချက်",
  "Savings Goal": "စုဆောင်းငွေ ရည်မှန်းချက်",
  "Edit profile and financial settings":
    "ပရိုဖိုင်နှင့် ငွေကြေးဆိုင်ရာ ဆက်တင်များကို ပြင်ဆင်ရန်",
  "Save all changes": "ပြောင်းလဲမှုအားလုံးကို သိမ်းဆည်းမည်",
  Cancel: "မလုပ်တော့ပါ",
  Logout: "အကောင့်ထွက်ရန်",
  "Change photo": "ဓာတ်ပုံပြောင်းရန်",
  Remove: "ဖယ်ရှားရန်",
  "Add transaction": "ငွေစာရင်း ထည့်သွင်းရန်",
  "Edit transaction": "ငွေစာရင်း ပြင်ဆင်ရန်",
  Amount: "ပမာဏ",
  Category: "အမျိုးအစား",
  Uncategorized: "အမျိုးအစား မသတ်မှတ်ရသေး",
  Note: "မှတ်ချက်",
  "Delete transaction": "ငွေစာရင်း ဖျက်သိမ်းရန်",
  "Choose a new password": "စကားဝှက်အသစ် ရွေးချယ်ပါ",
  "New Password": "စကားဝှက်အသစ်",
  "Update password": "စကားဝှက်ကို ပြောင်းလဲမည်",
  "Set your starting capital": "အစပြုမတည်ငွေကို သတ်မှတ်ပါ",
  "Start tracking": "စတင်မှတ်တမ်းတင်မည်",
  "Financial insights": "ငွေကြေးဆိုင်ရာ သုံးသပ်ချက်များ",
  "A live view calculated from your real activity":
    "သင့်၏ တကယ့်ငွေကြေးလှုပ်ရှားမှုများမှ တွက်ချက်ထားသော လက်ရှိအခြေအနေ",
  "FINANCIAL HEALTH": "ငွေကြေးကျန်းမာရေးအခြေအနေ",
  "You are building momentum": "ငွေကြေးအင်အား တည်ဆောက်နိုင်နေပါပြီ",
  "You are making progress": "တိုးတက်မှုများ ရှိနေပါသည်",
  "A few changes can help": "အနည်းငယ် ပြင်ဆင်ခြင်းဖြင့် ပိုမိုကောင်းမွန်လာနိုင်ပါသည်",
  "Your score considers savings, budget pace, and yearly goal progress.":
    "ဤအမှတ်ပေးစနစ်သည် စုဆောင်းငွေ၊ ဘတ်ဂျက်သုံးစွဲနှုန်းနှင့် နှစ်စဉ်ရည်မှန်းချက် တိုးတက်မှုကို ထည့်သွင်းတွက်ချက်ထားသည်။",
  "Safe to spend": "စိတ်ချလက်ချ သုံးနိုင်သောငွေ",
  "Set a spending cap": "အသုံးစရိတ် ကန့်သတ်ချက် သတ်မှတ်ပါ",
  "Savings rate": "စုဆောင်းနှုန်း",
  "Needs income data": "ဝင်ငွေအချက်အလက် လိုအပ်နေပါသည်",
  "MONTHLY SPENDING PACE": "လစဉ် အသုံးစရိတ်နှုန်း",
  "No cap set": "ကန့်သတ်ချက် မရှိသေးပါ",
  "On pace": "သတ်မှတ်နှုန်းအတွင်း ရှိသည်",
  "Above pace": "သတ်မှတ်နှုန်းထက် ကျော်လွန်နေသည်",
  "You have spent {spent} of your {cap} monthly cap.":
    "လစဉ်ကန့်သတ်ငွေ {cap} ထဲမှ {spent} သုံးစွဲထားပါသည်။",
  "Set a monthly spending cap in Profile to unlock pacing guidance.":
    "သုံးစွဲနှုန်း လမ်းညွှန်ချက်ရရှိရန် ပရိုဖိုင်တွင် လစဉ်ကန့်သတ်ငွေ သတ်မှတ်ပါ။",
  "YEARLY SAVINGS GOAL": "နှစ်စဉ် စုဆောင်းငွေ ရည်မှန်းချက်",
  "Goal: {goal}": "ရည်မှန်းချက် - {goal}",
  "Add a yearly goal in Profile to track your progress.":
    "တိုးတက်မှုကို စောင့်ကြည့်ရန် ပရိုဖိုင်တွင် နှစ်စဉ်ရည်မှန်းချက် ထည့်သွင်းပါ။",
  "This month at a glance": "ယခုလ တစ်ိုချုပ်",
  "Net cash flow": "အသားတင် ငွေသားစီးဆင်းမှု",
  "Top spending category": "အသုံးအများဆုံး အမျိုးအစား",
  "No spending yet": "အသုံးစရိတ် မရှိသေးပါ",
  "Compared with last month": "ပြီးခဲ့သည့်လနှင့် နှိုင်းယှဉ်ချက်",
  "Not enough history": "နှိုင်းယှဉ်ရန် မှတ်တမ်းမလုံလောက်ပါ",
  "CAPITAL + INCOME − EXPENSES": "မတည်ငွေ + ဝင်ငွေ − ထွက်ငွေ",
  "THIS MONTH": "ယခုလ",
  "Category Breakdown": "အမျိုးအစားအလိုက် ခွဲခြမ်းစိတ်ဖြာချက်",
  "TOTAL SPENT": "စုစုပေါင်း သုံးစွဲငွေ",
  "TOP CATEGORY": "အသုံးအများဆုံး အမျိုးအစား",
  "of spending": "အသုံးစရိတ်၏",
  Other: "အခြား",
  "NO CATEGORY SPENDING YET": "အမျိုးအစားအလိုက် အသုံးစရိတ် မရှိသေးပါ",
  "NO CATEGORY BUDGETS YET": "အမျိုးအစား ဘတ်ဂျက် မရှိသေးပါ",
  "TOTAL MONTHLY SPENDING": "စုစုပေါင်း လစဉ်အသုံးစရိတ်",
  "TOTAL MONTHLY INCOME": "စုစုပေါင်း လစဉ်ဝင်ငွေ",
  "TOTAL SPENDING FOR PERIOD": "ရွေးချယ်ထားသော ကာလအတွက် စုစုပေါင်းအသုံးစရိတ်",
  "TOTAL INCOME FOR PERIOD": "ရွေးချယ်ထားသော ကာလအတွက် စုစုပေါင်းဝင်ငွေ",
  "RECORDED CATEGORY BUDGETS": "မှတ်တမ်းတင်ထားသော အမျိုးအစားဘတ်ဂျက်များ",
  "REPORTING PERIOD": "အစီရင်ခံမည့်ကာလ",
  "Previous period": "ယခင်ကာလ",
  "Next period": "နောက်ကာလ",
  "Select month range": "လ အပိုင်းအခြားကို ရွေးချယ်ပါ",
  "Select reporting period": "အစီရင်ခံမည့်ကာလကို ရွေးချယ်ပါ",
  "Choose months and years only. Days are not included.":
    "လနှင့် နှစ်ကိုသာ ရွေးချယ်ပါ။ ရက်များ မပါဝင်ပါ။",
  "START MONTH": "စတင်မည့်လ",
  "END MONTH": "ပြီးဆုံးမည့်လ",
  "Previous year": "ယခင်နှစ်",
  "Next year": "နောက်နှစ်",
  "Apply month range": "လ အပိုင်းအခြားကို အသုံးပြုမည်",
  Month: "လ",
  Months: "လများ",
  "Tap a category to change its name, icon, color, or budget.":
    "အမည်၊ ပုံသင်္ကေတ၊ အရောင် သို့မဟုတ် ဘတ်ဂျက် ပြောင်းလဲရန် အမျိုးအစားကို နှိပ်ပါ။",
  "Create one below, then use it when adding a transaction.":
    "အောက်တွင် အသစ်ဖန်တီးပြီး ငွေစာရင်းထည့်သည့်အခါ အသုံးပြုပါ။",
  TRANSACTIONS: "ငွေစာရင်းများ",
  BUDGET: "ဘတ်ဂျက်",
  "Calculated only from your transactions":
    "သင့်ငွေစာရင်းများမှသာ တွက်ချက်ထားသည်",
  "NET INCOME VS EXPENSE": "အသားတင် ဝင်ငွေနှင့် ထွက်ငွေ နှိုင်းယှဉ်ချက်",
  "NO PREVIOUS DATA": "ယခင်အချက်အလက် မရှိပါ",
  "VS LAST YEAR": "ပြီးခဲ့သည့်နှစ်နှင့် နှိုင်းယှဉ်ချက်",
  "VS LAST MONTH": "ပြီးခဲ့သည့်လနှင့် နှိုင်းယှဉ်ချက်",
  "NO TRANSACTIONS IN THIS YEAR": "ယခုနှစ်အတွင်း ငွေစာရင်း မရှိပါ",
  "NO TRANSACTIONS IN THIS MONTH": "ယခုလအတွင်း ငွေစာရင်း မရှိပါ",
  "INCOME ENTRIES": "ဝင်ငွေ စာရင်းသွင်းမှုများ",
  "EXPENSE ENTRIES": "ထွက်ငွေ စာရင်းသွင်းမှုများ",
  "Search this period…": "ဤကာလအတွင်း ရှာဖွေရန်…",
  "NO REAL TRANSACTIONS TO SHOW": "ပြသရန် တကယ့်ငွေစာရင်း မရှိပါ",
  "Enter valid MMK amounts": "မှန်ကန်သော ကျပ်ငွေပမာဏကို ထည့်သွင်းပါ",
  "Could not save profile": "ပရိုဖိုင်ကို သိမ်းဆည်း၍မရပါ",
  "Could not save language": "ဘာသာစကား ဆက်တင်ကို သိမ်းဆည်း၍မရပါ",
  "Photo permission needed": "ဓာတ်ပုံအသုံးပြုခွင့် လိုအပ်သည်",
  "Allow photo-library access to choose an avatar.":
    "ပရိုဖိုင်ပုံရွေးချယ်ရန် ဓာတ်ပုံပြခန်းကို အသုံးပြုခွင့်ပေးပါ။",
  "Could not read this image": "ဤပုံကို ဖတ်ရှု၍မရပါ",
  "Remove avatar?": "ပရိုဖိုင်ပုံကို ဖယ်ရှားမည်လား?",
  "Your uploaded avatar will be deleted.":
    "သင်တင်ထားသော ပရိုဖိုင်ပုံ ဖျက်ဆီးခံရပါမည်။",
  "Your Profile": "သင့်ပရိုဖိုင်",
  "Uploading…": "တင်နေသည်…",
  "FULL NAME": "အမည်အပြည့်အစုံ",
  "PHONE NUMBER": "ဖုန်းနံပါတ်",
  "Phone Number": "ဖုန်းနံပါတ်",
  "Not added": "မထည့်ရသေးပါ",
  "OPENING • STARTING CAPITAL": "အစပြု • မတည်ငွေ",
  "Changing this recalculates the current balance.":
    "ဤအရာကို ပြောင်းလဲခြင်းဖြင့် လက်ရှိလက်ကျန်ငွေကို ပြန်လည်တွက်ချက်မည်ဖြစ်သည်။",
  "MONTHLY • SPENDING CAP": "လစဉ် • အသုံးစရိတ် ကန့်သတ်ချက်",
  "ACTUAL SPENDING": "အမှန်တကယ် သုံးစွဲငွေ",
  "YEARLY • SAVINGS GOAL": "နှစ်စဉ် • စုဆောင်းငွေ ရည်မှန်းချက်",
  "YEAR NET": "နှစ်အလိုက် အသားတင်ငွေ",
  "Add activity to unlock your score": "အမှတ်စနစ်ကို ဖွင့်ရန် ငွေစာရင်း စတင်ထည့်သွင်းပါ",
  "Your score will appear after you add real income or expense activity.":
    "ဝင်ငွေ သို့မဟုတ် ထွက်ငွေ တကယ့်လှုပ်ရှားမှုများကို ထည့်သွင်းပြီးနောက် သင့်အမှတ် ပေါ်လာပါမည်။",
  Notifications: "အသိပေးချက်များ",
  "{count} unread alerts": "မဖတ်ရသေးသော အသိပေးချက် {count} ခု",
  "You are all caught up": "အသိပေးချက်အားလုံးကို ဖတ်ပြီးပါပြီ",
  "No alerts right now": "ယခုလက်ရှိ အသိပေးချက် မရှိပါ",
  "Important budget and goal updates will appear here.":
    "အရေးကြီးသော ဘတ်ဂျက်နှင့် ရည်မှန်းချက် အခြေအနေများကို ဤနေရာတွင် ပြသမည်ဖြစ်သည်။",
  "Mark all as read": "အားလုံးကို ဖတ်ပြီးဟု သတ်မှတ်မည်",
  "Monthly limit exceeded": "လစဉ် ကန့်သတ်ငွေ ကျော်လွန်သွားပါပြီ",
  "You have spent {spent}, which is above your {limit} limit.":
    "သတ်မှတ်ကန့်သတ်ငွေ {limit} ထက် ကျော်လွန်ပြီး {spent} သုံးစွဲထားပါသည်။",
  "Approaching your monthly limit": "လစဉ် ကန့်သတ်ငွေသို့ နီးကပ်လာပါပြီ",
  "You have used {percent}% of your spending limit.":
    "အသုံးစရိတ် ကန့်သတ်ငွေ၏ {percent}% ကို အသုံးပြုပြီး ဖြစ်ပါသည်။",
  "Category budget exceeded": "အမျိုးအစား ဘတ်ဂျက် ကျော်လွန်သွားပါပြီ",
  "{category} is {amount} over budget.":
    "{category} သည် ဘတ်ဂျက်ထက် {amount} ပိုသုံးမိနေပါသည်။",
  "Savings goal reached!": "စုဆောင်းငွေ ရည်မှန်းချက် ပြည့်မီပါပြီ!",
  "You reached your {goal} yearly savings goal.":
    "နှစ်စဉ်စုဆောင်းငွေ ရည်မှန်းချက် {goal} သို့ ပြည့်မီစွာ ရောက်ရှိပါပြီ။",
  "Transactions need attention": "ငွေစာရင်းများကို ပြန်လည်စစ်ဆေးရန် လိုအပ်သည်",
  "{count} transactions have no category.":
    "ငွေစာရင်း {count} ခုတွင် အမျိုးအစား မသတ်မှတ်ရသေးပါ။",
  "Device notifications enabled": "စက်ပစ္စည်း အသိပေးချက်များကို ဖွင့်ထားသည်",
  "Enable notifications in Settings": "ဆက်တင်များတွင် အသိပေးချက်များကို ဖွင့်ပါ",
  "Get alerts on this device": "ဤစက်ပစ္စည်းတွင် အသိပေးချက်များ ရယူပါ",
  "New financial alerts will appear on this device.":
    "ငွေကြေးဆိုင်ရာ အသိပေးချက်အသစ်များ ဤစက်တွင် ပေါ်လာပါမည်။",
  "Receive budget and savings alerts outside the app.":
    "အက်ပ်အပြင်ဘက်တွင် ဘတ်ဂျက်နှင့် စုဆောင်းငွေ အသိပေးချက်များကို လက်ခံရယူပါ။",
  "Money, made clear": "ငွေကြေးစီမံမှုကို ရှင်းလင်းလွယ်ကူစေသည်",
  "AVAILABLE NOW": "လက်ရှိ သုံးနိုင်သောငွေ",
  "Opens the related page": "သက်ဆိုင်ရာ စာမျက်နှာကို ဖွင့်မည်",
  "Transaction details": "ငွေစာရင်း အသေးစိတ်",
  Back: "နောက်သို့",
  Expense: "ထွက်ငွေ",
  "Date and time": "နေ့စွဲနှင့် အချိန်",
  "No note added": "မှတ်ချက် မထည့်ထားပါ",
  "Editing or deleting this transaction recalculates all balances and reports.":
    "ဤငွေစာရင်းကို ပြင်ဆင်ခြင်း သို့မဟုတ် ဖျက်ခြင်းသည် လက်ကျန်ငွေနှင့် အစီရင်ခံစာအားလုံးကို ပြန်လည်တွက်ချက်မည်ဖြစ်သည်။",
  "Tap a transaction to view its details": "ငွေစာရင်းအသေးစိတ်ကို ကြည့်ရှုရန် နှိပ်ပါ",
  "Savings by year": "နှစ်အလိုက် စုဆောင်းငွေ",
  "Income minus expenses, compared with the goal recorded for each year.":
    "ဝင်ငွေမှ ထွက်ငွေကိုနှုတ်ကာ နှစ်အလိုက် မှတ်တမ်းတင်ထားသော ရည်မှန်းချက်နှင့် နှိုင်းယှဉ်ထားသည်။",
  "OF GOAL": "ရည်မှန်းချက်၏",
  "NO GOAL RECORDED": "ရည်မှန်းချက် မှတ်တမ်းတင်ထားခြင်း မရှိပါ",
  INCOME: "ဝင်ငွေ",
  EXPENSES: "ထွက်ငွေ",
  GOAL: "ရည်မှန်းချက်",
  "Monthly limit history": "လစဉ် ကန့်သတ်ငွေ မှတ်တမ်း",
  "NO LIMIT HISTORY RECORDED": "ကန့်သတ်ငွေ မှတ်တမ်း မရှိသေးပါ",
};
const Context = createContext<{
  language: Language;
  setLanguage: (v: Language) => void;
  t: (s: string) => string;
}>({ language: "en", setLanguage: () => {}, t: (s) => s });
export function LanguageProvider({ children }: PropsWithChildren) {
  const [language, setValue] = useState<Language>("en");
  useEffect(() => {
    AsyncStorage.getItem("clarity-language").then((v) => {
      if (v === "en" || v === "my") setValue(v);
    });
  }, []);
  const value = useMemo(
    () => ({
      language,
      setLanguage: (v: Language) => {
        setValue(v);
        AsyncStorage.setItem("clarity-language", v);
      },
      t: (s: string) => (language === "my" ? (my[s] ?? s) : s),
    }),
    [language],
  );
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export const useLanguage = () => useContext(Context);
