import { PropsWithChildren, ReactNode } from 'react';
import { Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../contexts/ThemeContext';
import { fonts, shadow } from '../theme';

export function Card({ children, style }: PropsWithChildren<{ style?: object }>) { const { palette } = useTheme(); return <View style={[s.card, shadow, { backgroundColor: palette.card, borderColor: palette.border }, style]}>{children}</View>; }
export function Label({ children, style }: PropsWithChildren<{ style?: object }>) { const { palette } = useTheme(); return <Text style={[s.label, { color: palette.muted }, style]}>{children}</Text>; }
export function Title({ children, style }: PropsWithChildren<{ style?: object }>) { const { palette } = useTheme(); return <Text style={[s.title, { color: palette.text }, style]}>{children}</Text>; }
export function Button({ title, onPress, secondary, icon, disabled }: { title: string; onPress: () => void; secondary?: boolean; icon?: keyof typeof Ionicons.glyphMap; disabled?: boolean }) { const { palette } = useTheme(); return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, { backgroundColor: secondary ? 'transparent' : palette.primary, borderColor: palette.primary, opacity: disabled ? .5 : 1, transform: [{ scale: pressed ? .98 : 1 }] }]}>{icon && <Ionicons name={icon} size={20} color={secondary ? palette.primary : '#fff'} />}<Text style={[s.buttonText, { color: secondary ? palette.primary : '#fff' }]}>{title}</Text></Pressable>; }
export function Field(props: TextInputProps & { icon?: keyof typeof Ionicons.glyphMap }) { const { palette } = useTheme(); return <View style={[s.field, { backgroundColor: palette.input, borderColor: palette.border }]}>{props.icon && <Ionicons name={props.icon} size={20} color={palette.muted} />}<TextInput placeholderTextColor={palette.muted} {...props} style={[s.input, { color: palette.text }, props.style]} /></View>; }
export function Progress({ value, danger }: { value: number; danger?: boolean }) { const { palette } = useTheme(); return <View style={[s.track, { backgroundColor: palette.primarySoft }]}><View style={[s.fill, { width: `${Math.min(100, Math.max(2, value))}%`, backgroundColor: danger ? palette.danger : palette.success }]} /></View>; }
export function Empty({ icon, title, text }: { icon: keyof typeof Ionicons.glyphMap; title: string; text: string }) { const { palette } = useTheme(); return <View style={s.empty}><Ionicons name={icon} size={38} color={palette.muted}/><Title style={{fontSize:18}}>{title}</Title><Label style={{textAlign:'center'}}>{text}</Label></View>; }
const s = StyleSheet.create({ card:{borderWidth:1,borderRadius:16,padding:18},label:{fontFamily:fonts.mono,fontSize:12,lineHeight:18},title:{fontFamily:fonts.bold,fontSize:24,lineHeight:32},button:{height:52,borderRadius:10,borderWidth:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:9},buttonText:{fontFamily:fonts.semibold,fontSize:16},field:{height:54,borderRadius:10,borderWidth:1,paddingHorizontal:14,alignItems:'center',flexDirection:'row',gap:10},input:{flex:1,fontFamily:fonts.regular,fontSize:16},track:{height:8,borderRadius:8,overflow:'hidden'},fill:{height:'100%',borderRadius:8},empty:{alignItems:'center',padding:32,gap:8} });
